### ISSUE TITLE
Plugin Connection Timeout crashing Homebridge

### ISSUE THREAD

**Issue by inzlabs** [kyleaa/homebridge-samsungtv2016#15] opened 2017-01-14 16:18 UTC
I would like to start by saying thank you Kyleaa. So far your work on this plugin has been great. 

After the last update, where with the last Samsung tv's it is possible to turn on and off the screen, looks like it brought an issue that affects the whole Homebridge app.

I am not a developer, but I managed to get the log before it crashes. Looks like it is something related to the plugin trying to check on the TV but not response back. What I am sure is that there was no response because the TV was off. When the TV is on, and all the time it is running, the plug-in doesn't crash Homebridge.

Here is the log:
```
pi@raspberrypi:~ $ homebridge 
*** WARNING *** The program 'nodejs' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs>
*** WARNING *** The program 'nodejs' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=nodejs&f=DNSServiceRegister>
[1/13/2017, 7:37:13 PM] Loaded plugin: homebridge-nest
[1/13/2017, 7:37:13 PM] Registering platform 'homebridge-nest.Nest'
[1/13/2017, 7:37:13 PM] ---
[1/13/2017, 7:37:14 PM] Loaded plugin: homebridge-samsungtv2016
[1/13/2017, 7:37:14 PM] Registering accessory 'homebridge-samsungtv.SamsungTV2016'
[1/13/2017, 7:37:14 PM] ---
[1/13/2017, 7:37:14 PM] Loaded config.json with 1 accessories and 1 platforms.
[1/13/2017, 7:37:14 PM] ---
[1/13/2017, 7:37:14 PM] Loading 1 platforms...
[1/13/2017, 7:37:14 PM] Initializing Nest platform...
[1/13/2017, 7:37:14 PM] Fetching Nest devices.
[1/13/2017, 7:37:14 PM] Loading 1 accessories...
[1/13/2017, 7:37:14 PM] [TV Living room] Initializing SamsungTV2016 accessory...
[1/13/2017, 7:37:15 PM] Software version for Living Room Thermostat (nesty) is: 5.6-7
[1/13/2017, 7:37:15 PM] Temperature unit for Living Room Thermostat (nesty) is: Fahrenheit
[1/13/2017, 7:37:15 PM] Current temperature for Living Room Thermostat (nesty) is: 68 F
[1/13/2017, 7:37:15 PM] Current humidity for Living Room Thermostat (nesty) is: 50%
[1/13/2017, 7:37:15 PM] Target temperature for Living Room Thermostat (nesty) is: 68 F
[1/13/2017, 7:37:15 PM] Away for Living Room Thermostat (nesty) is: 0
[1/13/2017, 7:37:15 PM] Initializing platform accessory 'Living Room Thermostat (nesty)'...
Scan this code with your HomeKit App on your iOS device to pair with Homebridge:
                       
    ┌────────────┐     
    │ 031-45-154 │     
    └────────────┘     
                       
[1/13/2017, 7:37:16 PM] Homebridge is running on port 51826.
[1/13/2017, 7:38:10 PM] [TV Living room] received on command: 1
[1/13/2017, 7:38:10 PM] [TV Living room] TV API is active
[1/13/2017, 7:38:10 PM] [TV Living room] sending power key
[1/13/2017, 7:38:10 PM] [TV Living room] websocket connect
[1/13/2017, 7:38:10 PM] [TV Living room] successfully powered on tv
[1/13/2017, 7:38:11 PM] [TV Living room] websocket closed
[1/13/2017, 7:38:17 PM] [TV Living room] received on command: 0
[1/13/2017, 7:38:17 PM] [TV Living room] sending power key
[1/13/2017, 7:38:17 PM] [TV Living room] websocket connect
[1/13/2017, 7:38:17 PM] [TV Living room] successfully powered off tv
[1/13/2017, 7:38:18 PM] [TV Living room] websocket closed
[1/13/2017, 7:38:28 PM] [TV Living room] received on command: 1
[1/13/2017, 7:38:28 PM] [TV Living room] TV API is active
[1/13/2017, 7:38:28 PM] [TV Living room] sending power key
[1/13/2017, 7:38:28 PM] [TV Living room] websocket connect
[1/13/2017, 7:38:28 PM] [TV Living room] successfully powered on tv
[1/13/2017, 7:38:29 PM] [TV Living room] websocket closed
[1/13/2017, 7:57:09 PM] [TV Living room] received on command: false
[1/13/2017, 7:57:09 PM] [TV Living room] sending power key
[1/13/2017, 7:57:09 PM] [TV Living room] websocket connect
[1/13/2017, 7:57:09 PM] [TV Living room] successfully powered off tv
[1/13/2017, 7:57:10 PM] [TV Living room] websocket closed
[1/13/2017, 8:13:53 PM] [TV Living room] No response from TV
[1/13/2017, 8:29:37 PM] [TV Living room] No response from TV
[1/13/2017, 8:29:41 PM] [TV Living room] No response from TV
[1/13/2017, 8:31:48 PM] [TV Living room] No response from TV
[1/13/2017, 9:10:30 PM] [TV Living room] No response from TV
[1/13/2017, 9:17:10 PM] Away for Living Room Thermostat (nesty) is: 1
[1/13/2017, 10:25:44 PM] Current humidity for Living Room Thermostat (nesty) is: 45%
[1/13/2017, 10:51:34 PM] Current humidity for Living Room Thermostat (nesty) is: 50%
[1/14/2017, 1:55:43 AM] Current humidity for Living Room Thermostat (nesty) is: 45%
[1/14/2017, 2:11:34 AM] Away for Living Room Thermostat (nesty) is: 0
[1/14/2017, 2:11:36 AM] Current temperature for Living Room Thermostat (nesty) is: 67 F
[1/14/2017, 2:17:36 AM] Current heating for Living Room Thermostat (nesty) is: Heating
[1/14/2017, 2:17:36 AM] Target temperature for Living Room Thermostat (nesty) is: 72 F
[1/14/2017, 2:17:36 AM] Target heating for Living Room Thermostat (nesty) is: Heating/Cooling
[1/14/2017, 2:18:38 AM] Current temperature for Living Room Thermostat (nesty) is: 68 F
[1/14/2017, 2:25:10 AM] Current temperature for Living Room Thermostat (nesty) is: 69 F
[1/14/2017, 2:25:19 AM] Target temperature for Living Room Thermostat (nesty) is: 71 F
[1/14/2017, 2:25:19 AM] Target temperature for Living Room Thermostat (nesty) is: 70 F
[1/14/2017, 2:27:09 AM] [TV Living room] No response from TV
[1/14/2017, 2:30:24 AM] Current temperature for Living Room Thermostat (nesty) is: 70 F
[1/14/2017, 2:32:12 AM] [TV Living room] No response from TV
[1/14/2017, 2:32:24 AM] Current heating for Living Room Thermostat (nesty) is: Off
[1/14/2017, 2:39:07 AM] Current temperature for Living Room Thermostat (nesty) is: 71 F
[1/14/2017, 2:42:33 AM] Current temperature for Living Room Thermostat (nesty) is: 70 F
[1/14/2017, 2:53:47 AM] [TV Living room] No response from TV
[1/14/2017, 3:02:15 AM] [TV Living room] No response from TV
[1/14/2017, 3:56:59 AM] [TV Living room] No response from TV
[1/14/2017, 4:52:42 AM] Current temperature for Living Room Thermostat (nesty) is: 71 F
[1/14/2017, 4:56:00 AM] [TV Living room] No response from TV
[1/14/2017, 5:01:38 AM] [TV Living room] No response from TV
[1/14/2017, 5:07:08 AM] Current temperature for Living Room Thermostat (nesty) is: 70 F
[1/14/2017, 5:17:15 AM] Current temperature for Living Room Thermostat (nesty) is: 71 F
[1/14/2017, 5:32:00 AM] [TV Living room] No response from TV
[1/14/2017, 6:00:05 AM] Current temperature for Living Room Thermostat (nesty) is: 70 F
[1/14/2017, 6:27:12 AM] Current temperature for Living Room Thermostat (nesty) is: 69 F
[1/14/2017, 6:33:24 AM] Current heating for Living Room Thermostat (nesty) is: Heating
[1/14/2017, 6:38:17 AM] Target temperature for Living Room Thermostat (nesty) is: 71 F
[1/14/2017, 6:38:26 AM] Target temperature for Living Room Thermostat (nesty) is: 69 F
[1/14/2017, 6:38:36 AM] Current heating for Living Room Thermostat (nesty) is: Off
[1/14/2017, 6:38:36 AM] Target temperature for Living Room Thermostat (nesty) is: 68 F
[1/14/2017, 6:39:12 AM] [TV Living room] No response from TV
[1/14/2017, 6:43:55 AM] [TV Living room] No response from TV
[1/14/2017, 6:48:07 AM] Current temperature for Living Room Thermostat (nesty) is: 70 F
[1/14/2017, 6:52:28 AM] [TV Living room] No response from TV
[1/14/2017, 6:56:33 AM] Current temperature for Living Room Thermostat (nesty) is: 69 F
[1/14/2017, 7:03:13 AM] [TV Living room] received on command: 0
[1/14/2017, 7:03:13 AM] [TV Living room] sending power key
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: connect ETIMEDOUT 192.168.1.13:8001
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1087:14)
pi@raspberrypi:~ $ 

```

If there is something I could help to solve this, count with me. 

Thank you for your time.

**Comment by kyleaa** [comment] 2017-01-14 16:42
This is a duplicate of Issue #6

**Closed as completed by kyleaa** 2017-01-14 16:42 UTC
